services:
  - type: web
    name: nirdosh-databricks-api
    env: python
    region: Ohio
    plan: free

    buildcommand: "pip install -r requirements.txt"
    startcommand: "bash start.sh"

    healthCheckPath: /

    envVars:
      - key: API_KEY
        sync: false
      - key: DATABRICKS_HOST
        sync: false
      - key: DATABRICKS_TOKEN
        sync: false
      - key: DATABRICKS_CLUSTER_ID
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
    
    autoDeploy: true