resources:
  jobs:
    city_order_pipeline:
      name: city-order-pipeline

      permissions:
        - group_name: nirdosh_job_runners_group
          level: CAN_MANAGE_RUN

      tags:
        project: city-order
        owner: nirdosh
      
      tasks:
        - task_key: ingest
          notebook_task:
            notebook_path: src/main
            base_parameters:
              VOLUME_PATH: ${var.volume_path}
              CATALOG: ${var.catalog}
              SCHEMA: ${var.schema}
              ENV: ${bundle.target}
          environment_key: default
        
        - task_key: transform
          depends_on:
            - task_key: ingest
          spark_python_task:
            python_file: ../../src/transformation/transform_orders.py
          environment_key: default

        - task_key: validate
          depends_on: 
            - task_key: transform
          spark_python_task:
            python_file: ../../src/validation/validate_orders.py
          environment_key: default
        
      environments:
        - environment_key: default
          spec:
            environment_version: "4"
      