common_params: &common_params
  - "--catalog"
  - ${var.catalog}
  - "--schema"
  - ${var.schema}
  - "--volume_path"
  - ${var.volume_path}
  
resources:
  jobs:
    city_order_pipeline:
      name: city-order-pipeline

      permissions:
        - group_name: nirdosh_job_runners_group
          level: CAN_MANAGE_RUN

      tags:
        project: city-order
        owner: nirdosh
      
      tasks:
        - task_key: ingest
          spark_python_task:
            python_file: ../../src/ingestion/ingest_orders.py
            parameters: *common_params
          environment_key: default
        
        - task_key: transform
          depends_on:
            - task_key: ingest
          spark_python_task:
            python_file: ../../src/transformation/transform_orders.py
            parameters: *common_params
          environment_key: default

        - task_key: validate
          depends_on: 
            - task_key: transform
          spark_python_task:
            python_file: ../../src/validation/validate_orders.py
            parameters: *common_params
          environment_key: default
        
      environments:
        - environment_key: default
          spec:
            environment_version: "4"
      